### ISSUE TITLE
9.29. 회의 안건

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#102]
* 각자 파트 작업 진행상황 공유

추가하고 싶은 안건은 댓글로 적어주세요 !! 😊

**Comment by bwmelon97** [comment]
* Board 페이지 사이드 컴포넌트에 들어갈 기능

**Comment by pec9399** [comment]
- 다음 회의 전까지 할 작업 공유
- Issue로 작업 요청시 소통 원활화 하는 방법? 토의

**Comment by thn02046** [comment]
* 담당 기능별 상세 기획 공유
* 페이지 기획 단계에서의 고민 토의
