### ISSUE TITLE
[Board] 게시판 페이지 기능 구현

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#103]
### 기획 Issue - #68 

- path 관련 기능
  - [x] path에 params로 board_id를 얻어내 board의 데이터 요청
  - [x] board의 커뮤니티와 user의 커뮤니티가 다른 경우, 홈 화면으로 Redirect
- [x] Construct BoardView Page Structure(Skeleton Code)
- [x] 글 생성 버튼 (Create Post 페이지로 이동)
- [x] List Item (Post Item) 컴포넌트 제작
  아이콘, 제목, 내용 일부, 작성 시각, 작성자, 추천수, 댓글수, 이미지 썸네일, 모집상태
- [x] Pagination
- [x] 검색 / 내가 쓴 글
- [ ] 상단 고정 기능
- [ ] #128

**Comment by pec9399** [comment]
> board의 커뮤니티와 user의 커뮤니티가 다른 경우, 홈 화면으로 Redirect

이거 같은 경우 서버쪽에서 session 에 담겨져있는 본인의 부대의 board와 그 board의 권한을 확인하여 리스트를 보내겠습니다. 권한이 없는데 조회한 경우 result: 'fail', message: 'not authenticated' 뭐 이런식으로? 반환하거나 그냥 빈 리스트를 반환하거나 하면 될 것 같습니다

**Comment by bwmelon97** [comment]
Mobile에서 Pagination이 무한 스크롤 방식으로 작동하도록 구현하는 것은 반응형 디자인을 넘어서 module logic의 추가가 필요한 많은 비용이 드는 작업이기 때문에 task에서 제외하였습니다.

나중에 작업을 할 여유가 된다면 다시 작업에 추가하겠습니다.

**Comment by bwmelon97** [comment]
Bug: Pagination과 검색 API 실행 할 때, 페이지 전체에 대한 렌더링에 영향 없이 PostListBox 만 Loading state로 변경하도록 할 것.

**Comment by bwmelon97** [comment]
상단 고정 기능은 게시판 관리 페이지 구현 후 진행하겠습니다.
사이드 컴포넌트도 추후에 제작하겠습니다.
