### ISSUE TITLE
웹 초기 페이지

### ISSUE THREAD

**Issue by thn02046** [osamhack2021/WEB_Millage_ICM#143]
![웹_초기페이지](https://user-images.githubusercontent.com/74306340/135745553-8c5e25e8-7a2e-46e8-bb1f-6adcdcb5204d.jpg)

추가 수정 예정입니다.(현재 생성 부대 표시 및 세부 디자인)

**Comment by pec9399** [comment]
'스마트한 군 생활의 시작, 밀리지' 이 파트 중앙에 맞춰도 상관없을까요? 그리고 아래에 footer도 왼쪽에 있는게 좀 이상해보입니다.

**Comment by bwmelon97** [comment]
'스마트한 군 생활의 시작, 밀리지' 배경으로 들어갈 사진이 있으면 좋을 것 같습니다.

**Comment by thn02046** [comment]
@bwmelon97 작년 작품들을 보면 국방홍보지원대원(연예병사)들의 이미지를 많이 사용했고, 이게 괜찮다 싶어서 국방 홍보원을 잘 찾아봤는데도 사진을 찾기가 힘드네요. 적당한 사진을 빨리 찾아보도록 하겠습니다.

@pec9399 이미지 추가하는대로 텍스트 위치 알맞게 조정하겠습니다. footer 중앙으로 수정하였습니다.
