### ISSUE TITLE
[Design] Main Page 기획

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#147]
### Board Header 컴포넌트
  - Global NavBar 바로 아래 위치하여, 전체 게시판 리스트를 보여주는 컴포넌트
  - Board Main / Board View / Post View 페이지에 공동으로 들어가기 (Create Post 페이지도 ?)
  - Mobile에서는 Accordion 컴포넌트
### Main Body 컴포넌트
  - 공모전 포스터 / 부대 행사 관련 이미지 컴포넌트 (해당 공지 게시글로 연결)
  - [게시판 제목 + 게시글 4개] 컴포넌트 그리드 (PC: 2 x n / Mobile: 1 x n)
  - 모바일에서는 게시판 제목만 보여지게 (게시글 X)
  - 고정 게시판: 공지, 자유, 칭찬, 민원
  - 관리자: 게시판 생성 버튼 / 게시판 관리 버튼 / 메인 페이지에 띄울 게시판 선택 및 순서 변경

### 우측 사이드 컴포넌트 - Board Main / Board View / Post View 페이지에 공동
  - 다가오는 일정
    날짜 기준이 아닌, 일정 기준
    개인 일정 / 부대 일정은 색깔로 구분
  - 자주 이용하는 게시판
  - 최근에 올라온 모집 게시글

---

![image](https://user-images.githubusercontent.com/39655003/135757915-ede3c582-f600-4640-811e-949b68509f1b.png)
![image](https://user-images.githubusercontent.com/39655003/135757818-52348231-a32d-4587-8ec0-a247b087e076.png)

---

로그인 직후 보여지는, Millage Logo를 클릭했을 때 이동되는, 게시판 탭을 클릭했을 때 나타나는 페이지입니다.

게시판의 메인 페이지이기도 하지만, **부대 커뮤니티의 메인 페이지**이기도 하기 때문에 게시판 파트에서만
기획하기보다는 팀원분들과 함께 기획하는 것이 좋겠다고 생각했습니다. 

논의하고 싶은 부분은 다음과 같습니다.
- 에브리타임과 마찬가지로 Millage의 메인 페이지를 게시판 메인 페이지와 동일한 페이지로 할 것인가
- 게시판 탭의 메인페이지 or 홈페이지의 메인 페이지 ?
    - 게시판 관련 기능 (게시판 리스트, 게시판 그리드, 게시판 사이드 컴포넌트 등) 만 넣기 ?
    - 일정 및 시설 예약, 계정, 통합 게시판 등에 대한 컴포넌트도 추가 ?
    - 게시판 메인이 아니라 홈페이지의 메인이라 했을 때, 필요한 기능 및 컴포넌트
- 에브리타임 메인 페이지와 어느 정도의 유사도까지 괜찮은지
- 기타 메인 페이지에 관한 의견

**Comment by pec9399** [comment]
오른쪽 사이드바는 지난번에 회의한 내용대로 하면 될 것 같고, 왼쪽 사이드바는 없어도 될 것 같다는 생각이 듭니다 (기능자체는 GNB에 있는 버튼으로 충분할 것 같습니다). 메인 화면에는 올려주신 예시대로 고정 게시판이 될 공지사항, 자유게시판, 칭찬게시판 등이 고정되면 좋을 것 같고, 혹은 가장 최신 게시글 몇개를 띄워주는 것도 괜찮을 것 같습니다.

**Comment by bwmelon97** [comment]
### 현재 기획

* Board Header 컴포넌트
  - Global NavBar 바로 아래 위치하여, 전체 게시판 리스트를 보여주는 컴포넌트
  - Board Main / Board View / Post View 페이지에 공동으로 들어가기 (Create Post 페이지도 ?)
  - Mobile에서는 Accordion 컴포넌트
* Main Body 컴포넌트
  - [게시판 제목 + 게시글 4개] 컴포넌트 그리드 (PC: 2 x n / Movile: 1 x n)
  - 고정 게시판: 공지, 자유, 칭찬, 민원
  - 최신 게시글 ?
* 우측 사이드 컴포넌트 - Board Main / Board View / Post View 페이지에 공동
  - 다가오는 일정
    날짜 기준이 아닌, 일정 기준
    개인 일정 / 부대 일정은 색깔로 구분
  - 자주 이용하는 게시판
  - 최근에 올라온 모집 게시글

**Comment by bwmelon97** [comment]
부대 관리자인 경우, 게시판 생성 / 관리 페이지로 이동할 수 있는 버튼과 게시판 Grid의 배열 등을 변경할 수 있는 기능이 추가되어야 할 것 같습니다.

**Comment by pec9399** [comment]
자주 이용하는 게시판기능의 우선순위를 뒤로 밀어야 된다면 밀어도 좋을 것 같습니다. 게시판 Grid의 배열을 변경한다는게 메인페이지에서의 Grid 인가요? 그렇게 까지 자유도를 줄 필요는 없을 것 같다는 생각이 드네요.

**Comment by bwmelon97** [comment]
![image](https://user-images.githubusercontent.com/39655003/135859143-bf0456df-e328-4c6e-aaa3-7137e62ce7bd.png)
Grid는 해당 이미지의 컴포넌트들의 배열을 의미한 것입니다.
게시판의 순서를 부대 관리자가 정할 수 있으면 좋을 것 같습니다. 
예시: [공지 - 자유 - 칭찬 - 모집 - 설문] -> [칭찬 - 공지 - 자유 - 모집 - 설문] 으로 순서 변경
