### ISSUE TITLE
9.19 회의 안건

### ISSUE THREAD

**Issue by pec9399** [osamhack2021/WEB_Millage_ICM#18]
1. Issue에 올라온 기능 검토, 핵심 기능 정리, 차별성 검토 (비즈니스 모델 포함) 
2. 핵심 기능에 따른 업무 분배, Milestone 정리
3. 해커톤 참여기간 동안 지킬 Ground rules 확립

**Comment by bwmelon97** [comment]
1번 안건에서 Issue에 올라온 아이디어를 구분해 보았습니다.

### 기본 기능
- 로그인 / 회원 가입 (소속 부대 인증)
- 커뮤니티 생성

### 프로젝트 아이디어
- 게시판의 개설방법 논의
- 전군 통합 게시판
- 서비스 컨테이너화

### 게시판 아이디어
- 민원게시판
- 인원 모집 게시판
- 공지 게시판
- 칭찬 게시판
- 건의 및 고충 사항 전달
- 공용시설 예약 시스템
- 공동 프로젝트(자기계발 독려)
- 분대위키

### 비게시판 아이디어
- 당직일정표
- Direct Message

**Comment by pec9399** [comment]
역할 분배를 위해 기능을 정리하였습니다.

## 게시판 기능 정리
### 사용자
- 실명/익명 게시글 생성 및 댓글 추가
- 본인 게시글, 댓글 수정/삭제
- 추천 기능
- 신고 기능
- 게시판 유형/컴포넌트 선택: 일반 게시판, 설문조사, 인원 모집, 위키

### 관리자
- 게시판 생성 / 삭제
- 게시글 생성 / 삭제
- 게시판 관리자 권한 부여
- 공지 게시글 등록 (상단 고정 게시글 등록)

## 일정표 기능 정리
- 당직 일정표
  - google calendar와 비슷한 기능 (달력 생성, 공유)
- 공용 시설 예약 시스템 ([SKKU Seminar Room 예약 시스템](https://scg.skku.ac.kr/seminar/) - 저희 학교에서 쓰는 시스템인데 별로긴 하지만 조금은 참고할 수 있을 것 같아 남겨둡니다)
  - 시설 추가
    - 승인방식 (선착순, 관리자 승인 등) 선택
    - 예약 가능한 날짜 (예: 1주일 전) 선택
    - 최대 인원 수 선택
  - 시설별 날짜 별 시간대 별 예약 시스템 
  - 사용자 정보에 등록된 메일, 휴대폰 등으로 알림?
  
## DM 기능 정리
  #6
