### ISSUE TITLE
[API] Board Entity 관련 수정 요청

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#190]
### [소스코드1 (board.entity.ts)](https://github.com/osamhack2021/WEB_Millage_ICM/blob/c3f467e311dc5b4039a407a712724320aaa3d8b1/application/millage-server/src/board/board.entity.ts)

* 글 쓰기 권한 데이터
https://github.com/osamhack2021/WEB_Millage_ICM/blob/c3f467e311dc5b4039a407a712724320aaa3d8b1/application/millage-server/src/board/board.entity.ts#L26-L27
해당 정보를 Enum으로 관리하는 게 좋을 것 같습니다.
0: 모든 유저 작성 가능
1: 관리자만 작성 가능

**Comment by nailerHeum** [comment]
사용가능이라는게 작성 권한에 대한 것일까요? 아니면 읽기 쓰기 둘다를 의미하는건가요?
일단 user_role과 같은 enum을 사용하도록 수정하겠습니다!

**Comment by nailerHeum** [comment]
user_role의 Role enum을 사용할 경우 ManyToMany 관계가 필요하게 되어, 일단은 말씀하신대로 0, 1로 작성했습니다.
```
export enum AuthType {
    ALL = 0,
    ADMIN = 1,
}
```

**Comment by nailerHeum** [comment]
main branch에 반영 되었습니다.
