### ISSUE TITLE
[Lint] lint 설정중 no-unused-vars 에 대한 설정

### ISSUE THREAD

**Issue by hig4342** [osamhack2021/WEB_Millage_ICM#197]
# [no-unused-vars](https://runebook.dev/ko/docs/eslint/rules/no-unused-vars)에 대한 lint 설정 변경에 대한 논의
함수 매개변수 중 사용하지 않음에도 항상 변수를 적어야 할 때가 있습니다.
그럴경우 underbar( _ ) 를 변수 이름 앞에 사용함으로써 미 사용 변수를 표시해주는 약속이 있습니다.
현재 lint 설정에는 해당 설정이 안 되어있습니다.
lint 변경은 모두의 약속이 이루어져야 하므로 이에 대한 의견을 남겨주셨으면 좋겠습니다.
해당 문서는 [argsignorepattern](https://eslint.org/docs/rules/no-unused-vars#argsignorepattern)에 있습니다.

**Comment by bwmelon97** [comment]
저는 해당 룰을 ignore 처리해도 좋다고 생각합니다.
