### ISSUE TITLE
Dependabot Security 이슈

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#20]
### We found potential security vulnerabilities in your dependencies.
You can see this message because you have been granted access to Dependabot alerts for this repository.

현재 프로젝트에 Dependabot에 의해 milage-client 디렉토리 내에 16개의 dependency들에서 security 취약성이 감지되었다는 배너가 나타났습니다.

프로젝트 레포를 public으로 설정하고, #19 PR을 merge하면서부터 발생한 이슈로 파악됩니다.

해당 PR에서 저는 `npx create-react-app template=typescript`로 프로젝트를 생성하고, `@craco/craco` 와 `craco-alias` 패키지를 설치했습니다.

개인 프로젝트를 진행할 당시에는 경험해보지 못한 이슈이기에, 해결하실 수 있는 분이 있는 지 여쭈어봅니다..😥

---

특이한 점은 `yarn audit` 명령어로 확인 했을 때, dependabot이 감지한 16건이 아닌
* `glob-parent` 에서 moderate 2건
* `browserslist` 에서 moderate 1건
총 3건 만이 확인 되었고, `yarn audit fix`로는 문제가 해결되지 않는다는 점입니다.

**Comment by pec9399** [comment]
일단 Dependabot 에서 자동으로 업데이트 하도록 설정해놓긴 해놓았습니다. 다만 제 의견으론 해커톤에 있어서 모든 패키지의 vulnerability를 크게 신경쓸 필요까지는 없어보입니다.
