### ISSUE TITLE
[API] 캘린더(schedule) API 요청

### ISSUE THREAD

**Issue by hig4342** [osamhack2021/WEB_Millage_ICM#242]
# Schedule API

### not nullable
* id: string / 일정이 많으므로 uuid가 좋을 것 같음
* title - string
* content - string
* start - Date
* userId - int / 유저와 1 - n 관계
* groupId: int / 개인일정일땐 전군게시판 id, 부대일정일땐 부대게시판 id 관계
### nullable
* end - Date | null / 일정이 당일만 있을경우: null, 여러날 있을경우: Date

### Request
* userId: int
* groupId: int
### Res
* schedule_list : Array<schedule> / userId가 맞으면서 groupid가 전군게시판인 일정 + groupid가 같은 일정

### Request
* groupId: int
### Res
* schedule_list : Array<schedule> / groupid가 같은 일정 5개(미확실)

### Request
* title - string
* content - string
* start - Date
* end - Date | null
* userId - int
* groupId - int
### Res
* message: 'success' | 'failed'

### Request
* id - string
* title - string
* content - string
* start - Date
* end - Date | null
* userId - int
### Res
* message: 'success' | 'failed'

### Request
* id - string
### Res
* message: 'success' | 'failed'

**Comment by nailerHeum** [comment]
확인했습니다! 구현하는대로 말씀드리겠습니다.
