### ISSUE TITLE
[API] RelationId 오류

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#253]
@nailerHeum 
https://github.com/osamhack2021/WEB_Millage_ICM/blob/3a1cc498b5370e040d17fa0cdf258fe51a1173b0/application/millage-server/src/post/post.entity.ts#L39-L40

#252 에서 RelationId와 관련된 오류가 있었습니다. (Code Review 중에 확인을 못했네요 ㅠㅠ)
`@RelationId` 데코레이터는 해당 Entity에서 Relation하는 property를 지정해주어야 합니다.
```ts
@RelationId((post: PostEntity) => post.writer) 
writerId: number; 
```

이 부분은 제가 수정해서 commit하겠습니다 !

**Comment by nailerHeum** [comment]
앗.. 저도 방금 확인했습니다 ㅠㅠ 죄송합니다.
