### ISSUE TITLE
[API] User PollItem relation 수정

### ISSUE THREAD

**Issue by nailerHeum** [osamhack2021/WEB_Millage_ICM#260]
- UserPollEntity 삭제
- ManyToMany decorator 사용

**Comment by bwmelon97** [comment]
* PollItem Entity의 `description` 프로퍼티를 `content`로 이름을 변경해주실 수 있을까요?
* `userPolls` 프로퍼티의 이름도 `votes`로 변경하면 좋을 것 같습니다.

**Comment by nailerHeum** [comment]
넵 같이 커밋하도록 하겠습니다.
