### ISSUE TITLE
DM 디자인 피드백

### ISSUE THREAD

**Issue by thn02046** [osamhack2021/WEB_Millage_ICM#276]
DM 디자인 완료 하였습니다. 피그마에서 우측 상단에 프로토타입 버튼 클릭하셔서 DM 프로토타입 진행해보시고 피드백 부탁드립니다. 완료후 커밋하겠습니다.
![image](https://user-images.githubusercontent.com/74306340/136693431-65dd8abe-e6eb-416e-b85a-ad9f00ef351b.png)
![DM초기화면](https://user-images.githubusercontent.com/74306340/136693571-c43c717e-9fdd-41c9-9f57-22d336140883.png)

![DM검색 후](https://user-images.githubusercontent.com/74306340/136693541-2bb27e60-9c90-4f8e-98d2-5ba31ecca4fa.png)
![DM사용중화면](https://user-images.githubusercontent.com/74306340/136693545-e392cb91-2345-4d8f-b805-16e44d1cbcf1.png)

![DM-받는사람검색1](https://user-images.githubusercontent.com/74306340/136693546-a77f6ea9-3dc7-48a1-b265-bd081f0f477e.png)

![DM-받는사람검색2](https://user-images.githubusercontent.com/74306340/136693585-5229ec44-1be6-4a04-8eaf-e38efd3f10c0.png)
![DM-채팅삭제](https://user-images.githubusercontent.com/74306340/136693549-bf38ca5d-0f46-456e-be31-e066d206ac61.png)
870b9e75.png)

**Comment by thn02046** [comment]
@pec9399 은찬님 확인해보시고 빠진부분 혹은 수정할부분 있으면 댓글로 남겨주세요 제가 연등시간에 디스코드 활용이 안될것 같습니다.

**Comment by pec9399** [comment]
@thn02046 받는사람 기능은 추가할 시간이 된다면 추가하도록 하겠습니다. 그 새로운 메시지 도착을 숫자형식으로 표기하는건 어떨까요? 지금 이미 새로운 메시지가 도착하면 숫자가 뜨도록 코드가 적용되어있을텐데 내일 서버가 켜지고 스크린샷 찍어서 보내드리도록 하겠습니다.
