### ISSUE TITLE
Login Routing

### ISSUE THREAD

**Issue by pec9399** [osamhack2021/WEB_Millage_ICM#31]
로그인
- Request: id, password

회원가입
- Request: id, name, password, email, etc. (To be added) 

아이디 중복 체크
- Request: id

**Comment by bwmelon97** [comment]
회원 가입 시, 소속 부대를 인증할 수 있으면 좋겠습니다 !

**Comment by pec9399** [comment]
네 에브리타임이랑 비슷하게 만들 계획입니다!

**Comment by nailerHeum** [comment]
구현된 내용 모두 확인했습니다. 코드 수정이 필요할 경우 다시 열겠습니다.
