### ISSUE TITLE
 프론트엔드 디렉토리 구조와 컴퍼넌트 작성 방식에 대한 안건

### ISSUE THREAD

**Issue by hig4342** [osamhack2021/WEB_Millage_ICM#35]
# 프론트엔드 관련 논의

## 안건 1 - 디렉토리 구조에 관한 통일성
lint 는 코드 작성 방식을 통일해주지만 디렉토리 구조를 어떻게 짜야할지는 가이드해주지 않습니다. 협업 개발하는데 있어 통일성은 그 무엇보다도 중요합니다

## 안건 2 - 컴퍼넌트 작성에 관한 통일성
현재 리액트 컴퍼넌트 작성방식이 두가지가 있습니다.  첫째로 Class형 컴퍼넌트, 둘째로 FC(함수형 컴퍼넌트)가 있습니다.
1번 방식의 장점에는 리액트 컴퍼넌트의 라이프사이클에 맞춰 개발할 수 있습니다.
단점으로는 최근에 나온 기술인 Hook을 사용하지 못합니다.
2번 방식의 장점에는 Hook을 사용할 수 있고, React 공식문서에서도 함수형 컴퍼넌트로 설명하고 있고 점점 함수형 컴퍼넌트로 설명하는 문서들이 많아지고 있습니다.
단점으로는 FC에 익숙하지 않으면 원하는 결과가 안나올 수도 있습니다.

**Comment by bwmelon97** [comment]
"컴포넌트 스타일 방법" 에 대해서도 논의하면 좋을 것 같습니다.

css-in-js 방법인 `styled-components`를 이용할 수도 있고, utility-first CSS framework 인 `tailwindcss`, 혹은 재사용가능한 UI 컴포넌트를 제공하는 `@mui/material`이나 `antd`와 같은 라이브러리를 사용할 수 있는데, 각자 어떤 방법이 편한지 논의를 해보면 좋을 것 같습니다.

**Comment by bwmelon97** [comment]
사용해본 React 관련 오픈소스 중 우리 프로젝트에서 사용하면 좋은 패키지를 공유해도 좋을 것 같습니다.

* `react-hook-form` https://react-hook-form.com/
* `fullcalendar` https://fullcalendar.io/
* ...

**Comment by bwmelon97** [comment]
React의 State 관리 라이브러리도 논의하면 좋을 것 같습니다.

* Redux
* Mobx
* Apollo-client
