### ISSUE TITLE
Millage 메인 페이지

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#36]
Millage의 메인 페이지의 구성이 필요할 것 같습니다.

* Header에 들어갈 카테고리
* Body 부분에 들어갈 게시판의 형태
* PC와 모바일 버전의 반응형 디자인

아래의 이미지는 에브리타임의 메인페이지 모습입니다.

![image](https://user-images.githubusercontent.com/39655003/134134587-2814d43c-1994-492b-a5c1-bf0adfa3a83a.png)

**Comment by pec9399** [comment]
일단 DM 같은경우는 Everytime / Instagram을 참고하면서 만들고 있습니다
