### ISSUE TITLE
업무 진행상황

### ISSUE THREAD

**Issue by thn02046** [osamhack2021/WEB_Millage_ICM#364]
### 웹
**로그인/회원가입** 
- [x] 랜딩페이지
- [x] 로그인
- [x] 회원가입

**DM**
 - [x] DM페이지
 - [x] 채팅삭제
 - [x] 채팅 알림
 
**게시판**
- [x] Board Main
- [ ] Post View
- [x] Create Board
- [x] Create Post
- [x] Board/Post Manage

**캘린더**
- [ ] 캘린더 페이지
- [ ] 시설 예약 페이지

**마이페이지**
- [ ] 관리자 마이페이지
- [ ] 사용자 마이페이지

### 모바일
**로그인/회원가입** 
- [x] 랜딩페이지
- [x] 로그인
- [x] 회원가입

**DM**
 - [ ] DM페이지
 - [ ] 채팅삭제
 - [ ] 채팅 알림
 
**게시판**
- [ ] Board Main
- [ ] Post View
- [ ] Create Board
- [ ] Create Post
- [ ] Board/Post Manage

**캘린더**
- [ ] 캘린더 페이지
- [ ] 시설 예약 페이지

**마이페이지**
- [ ] 관리자 마이페이지
- [ ] 사용자 마이페이지

**Comment by pec9399** [comment]
마이페이지 지금 그냥 모달로 띄우는데 한번 확인해보시겠어요? 좀 후순위로 미뤄도 될거같아요

**Comment by thn02046** [comment]
사이트 접속이 안됩니다
![image](https://user-images.githubusercontent.com/74306340/137072265-091c8b68-b6a3-49e4-ae25-52ee9c63250b.png)
