### ISSUE TITLE
[API] 캘린더 post API 수정

### ISSUE THREAD

**Issue by hig4342** [osamhack2021/WEB_Millage_ICM#397]
create 부분에서 유저를 세션에서 불러들일때
유저의 직책(일반 유저인지 관리자인지)도 같이 불러와서
`groupType`에 일반유저면 `GroupType.Person` 관리자면 `GroupType.UNIT` 이 들어가게 수정해주세요

**Comment by nailerHeum** [comment]
넵 지금 바로 하겠습니다
