### ISSUE TITLE
게시판 생성 기능 구현

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#43]
## 커뮤니티 관리자가 게시판을 생성할 수 있는 기능 & 페이지

현재 논의된 게시판 기능은 아래와 같습니다.
* 민원 / 칭찬 / 인원모집 / 설문 게시판 -> 자유게시판 (커스텀 가능)
* 공지 게시판
( --- )
* 전군 통합 게시판
* 고충 및 건의 게시판 (1대1)
* 분대 위키

이 중에서 **민원 / 칭찬 / 인원모집 / 설문 / 공지** 기능은 게시글의 기능 구분으로 게시판의 형태 및 디자인은 동일하게 가져가도 되겠다고 판단했습니다.

'자유게시판' 형태의 게시판의 모든 기능 (게시글 작성, 게시글 목록/개별 페이지, 게시글 관리) 이 완료된 이후에 다른 기능에 대한 게시판 생성 기능을 업데이트하겠습니다.

### 게시판 생성 Input
* **Title** - Text type
* **Description** - Text type
* **Authority to Write** (게시글 작성 권한) - Enum type [관리자, 모든 멤버]
  Enum 타입으로 선택한 이유는 권한의 종류가 늘어날 것을 대비하기 위함입니다.
* **Public/Private of writer's into** (작성자 공개 여부) - Boolean type
* **Allow Poll Posts** (설문 게시글 허용) - Boolean type
* **Allow Recruit Posts** (모집 게시글 허용) - Boolean type
* **Allow Add Image** (게시글에 이미지 업로드 허용) - Boolean type
* ... (추가로 필요한 내용은 댓글 부탁드립니다)

**Comment by nailerHeum** [comment]
자세히 작성해주셔서 감사합니다! 저는 이미지 첨부 기능이 추가적으로 필요하다고 생각합니다. 필요 여부를 검토해보고 필요하다면 이미지 갯수를 몇개까지 허용할 지, 이미지 용량은 얼마로 제한할 지 등 고민이 필요할 것 같습니다.

**Comment by bwmelon97** [comment]
피드백 감사합니다 !!

1. 이미지 첨부 허용 여부 추가하겠습니다.
2. 읽기 권한의 추가에 대해서는 팀 회의에서 논의해보면 좋을 것 같습니다. 현재 '관리자 / 병사' 2개로만 이루어진 사용자 그룹을 어떻게 더 세분화하면 좋을 지 논의가 필요할 듯 싶습니다 !

**Comment by bwmelon97** [comment]
모집 게시글을 따로 만들 필요가 없을 것 같다는 생각이 듭니다.\
OSAM 팀빌딩 게시판 처럼 참가 / 수락 / 거절 등을 따로 기능으로 만들지 않더라도 댓글 기능이 있으면 충분할 것 같습니다.
