### ISSUE TITLE
[API] CREATE Board API (게시판 생성 API)

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#44]
### `req`
- `community_id`: Int / 커뮤니티 id
- `CreateBoardInput`
    - `Title` - Text type
    - `Description` - Text type
    - `Authority to Write` (게시글 작성 권한) - Enum type [관리자, 모든 멤버]
      Enum 타입으로 선택한 이유는 권한의 종류가 늘어날 것을 대비하기 위함입니다.
    - `Public/Private of writer's into` (작성자 공개 여부) - Boolean type
    - `Allow Poll Posts` (설문 게시글 허용) - Boolean type
    - `Allow Recruit Posts` (모집 게시글 허용) - Boolean type
    - `Allow Add Image` (게시글에 이미지 업로드 허용) - Boolean type 

### `res`
- `board`: Board / 생성된 게시판 데이터

**Comment by nailerHeum** [comment]
#117 완료했습니다. 보완할 사항 있으면 다시 열어주세요!
