### ISSUE TITLE
[시연영상] 영상에서 시연할 기능

### ISSUE THREAD

**Issue by eunchan-park** [osamhack2021/WEB_Millage_ICM#497]
참고용으로 작성하였습니다. 모바일 부분이 들어가면 좋겠는 것들은 ****+모바일**** 로 명시를 해놨으나, 꼭 들어가야하는 것은 아닙니다.

기본적으로 시연은 https://millage.ml 도메인 상에서 하는 것이 좋을 것 같습니다.

동현님을 제외한 분들은 각자 시연을 위해 적절한 데이터들을 넣어주시기 바랍니다.

- 회원가입, 로그인 ****(+모바일)****
- 부대 생성 및 커뮤니티 확장성이 돋보이는 기능 (부대별 게시판, 테스트 시설, 공휴일 및 전군 공통 일정 자동 생성)
  - 부대 관리자의 게시판 추가
  - 부대 관리자의 시설 추가 
  - 유저 및 부대 생성이 승인 됐을 시 이메일 도착하는 기능
- 웹소켓을 통한 실시간 DM 기능 ****(+모바일)****
  - 사용자 목록 확인
  - 관리자와 소통, 병사들 간 소통
- 개인 일정을 관리하는 기능 ****(+모바일)****
- 시설 예약 확인 및 등록하는 기능 ****(+모바일)****
- 게시글 이용 ****(+모바일)****
  - 댓글 및 대댓글 확인, 댓글 작성, 좋아요, 삭제, 쪽지 (관리자는 모두 삭제 가능한 내용 포함)
- 부대 관리자 기능 (사용자 승인, 게시판 승인, 사용자 권한 관리 등)

**Comment by bwmelon97** [comment]
기능 시연영상 (화면상) 시연영상 전에, 실제로 밀리지를 사용하는 10-15초 분량의 시나리오를 5개 정도 넣고 시작하면 좋겠다는 생각이 들어요 !

### 시나리오
1. 병사의 당직 일정 확인
2. 조리장의 영내 장병 선호 급식 설문조사
3. 축구 인원 모집
4. 민원게시판
5. 칭찬게시판
6. DM

각각의 시나리오는 병사 및 간부가 출현하여 연기하고 5-10초 정도의 상황 연출 후, “OOO한 군생활엔, 밀리지” 문구의 나레이션으로 끝맺으면 어떨까 싶습니다.

시나리오별 시놉시스는 다음과 같습니다
### 당직일정표 확인
병사A: 이번주에 당직이 언제언제 있나 확인해 볼까? (밀리지의 당직 일정표 확인 후) 아잇, 내일이잖아 ! 이런...
(카메라 앵글 전환)
나레이션 : 스마트한 군생활엔, 밀리지 !
(병사A는 나레이션 나오는 타이밍에 카메라를 바라보며 엄지를 치켜세운다)
