### ISSUE TITLE
당직일정표

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#5]
# 당직일정표

## 개요

달력 UI가 제공되고, 날짜 칸에 직접 본인의 당직 일정을 입력하면 본인의 모든 당직 일정을 한눈에 확인할 수 있습니다.

군대 내에는 다양한 당직이 존재하고, 개개인의 병사들은 대부분 2~4개에 달하는 종류의 당직 개소를 책임집니다. (제주기지전대 기준) 하지만 각각의 당직명령표는 구분되어 있기 때문에 본인에게 할당된 당직일정을 모두 확인하기 위해서는 여러 개로 나뉘어 있는 게시판과 공문을 확인해야 합니다. 그렇기에 많은 병사들은 자신의 당직을 한 곳에 관리하기 위해 다이어리나 핸드폰의 기본 일정앱을 이용하곤 합니다.

밀리지의 당직일정표가 사용자에게 편한 UI/UX를 제공한다면 '자신의 모든 당직을 한 곳에서 확인하는 공간'의 표준이 될 수 있다고 생각합니다. 그렇게 된다면, 커뮤니티가 활성되기 이전에도 유저들이 꾸준히 밀리지에 방문할 수 있도록 유도할 수 있기에 Active User를 모으는데 효과적일 것이라 생각합니다.

## 논의가 필요한 부분

- 당직명령은 군사정보의 일종으로 만일 당직 일정표 화면을 캡처하여 SNS 등에 게시하면 보안상 문제가 될 수 있음.

## 기능 구현 (Todos)

- [ ]  달력 컴포넌트 (오픈소스 사용)
- [ ]  원하는 날짜에 당직을 추가하기
- [ ]  (선택) 입대 후 지금까지 근무한 당직 시간 알려주기
- [ ]  (선택) 다른 유저(동기 및 선후임)의 당직일정 확인 (서로 동의를 한 관계에서만)

**Comment by pec9399** [comment]
보안상의 문제를 해결하기 위해 일정정보를 부대별 코드 등를 이용해 암호화해서 저장하는 것도 좋을 것 같습니다 (타 부대 커뮤니티 이용자 혹은 데이터베이스 관리자가 특정 부대의 일정을 알지 못하도록)
