### ISSUE TITLE
게시판의 모집 게시글 기능 제외 논의

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#50]
* #43

현재 게시판 생성에는 모집 게시글 작성의 허용에 대한 input이 존재합니다.

자유게시판에서 모집 게시글 기능이 따로 필요가 없을 것 같다는 생각이 듭니다.
모집 게시글은 OSAM 팀빌딩 게시판을 참고하여 참가 / 수락 / 거절 등을 할 수 있는 게시글로 구상했지만,
각각의 기능들은 댓글로 충분히 대체될 수 있는 부분이라고 생각합니다.

다음 회의에서 논의 후, 게시판 생성 부분에서 제거 또는 유지를 결정하겠습니다.

**Comment by pec9399** [comment]
모집 게시글에 핵심 기능은 총 모집 인원수와 현재 모집된 인원 수 표시 여부인 것 같습니다. 다음 회의 때 한번 이야기 해보도록 하겠습니다.

**Comment by bwmelon97** [comment]
게시글 상태 (모집중, 모집완료)를 나타내는 것도 기능에 포함할 수 있겠네요 !

**Comment by bwmelon97** [comment]
모집 게시글 기능 넣기
