### ISSUE TITLE
1주차 진행 현황 공유

### ISSUE THREAD

**Issue by pec9399** [osamhack2021/WEB_Millage_ICM#53]
이번주 멘토님과의 회의 및 보고서 작성을 위해 1주차 진행 현황을 공유해주시기 바랍니다.

양식은 따로 없고 자유롭게 리스트형식이나 글로 작성해주시면 됩니다.

**Comment by bwmelon97** [comment]
1. 해커톤 기간 주차별 개인 목표 설정

|           | Create Board | Create Post | Board View | Post View | Manage |
| :-------: | :----------: | :---------: | :--------: | :-------: | :----: |
|   기획    |      O       |      O      |     -      |     -     |   -    |
| 기능 구현 |      O       |      -      |     -      |     -     |   -    |
| 스타일링  |      -       |      -      |     -      |     -     |   -    |
|    API    |      -       |      -      |     -      |     -     |   -    |

|          주차          | 목표                                                         |
| :--------------------: | ------------------------------------------------------------ |
|    ~ 9.24. (1주차)     | 개인 목표 설정 / Create Board, Create Post 기획 및 기능 구현 |
| 9.25 ~ 10. 1. (2주차)  | Board View, Post View, Manage 기획 및 기능 구현 / redux-saga 공부 |
| 10. 2 ~ 10. 8. (3주차) | 스타일링 & API 작업 (스타일링 - 평일 2일, 휴일 1일 당 1파트 / API - 평일 1파트, 휴일 2파트 예상) |
| 10. 9 ~ 10.15. (4주차) | 스타일링 & API 작업 완료 / Mock API 이용해서 통합, 1대1, 위키 게시판 중 1 |
| 10.16 ~ 10.20. (5주차) | 문서화 작업, 시연 영상 제작, PPT                             |

2. Create Board 기획 및 기능 구현 
    - #43 
    - #48

3. Create Post 기획
    - #49

**Comment by thn02046** [comment]
1. 웹, 앱 초기 페이지 구상 및 디자인
2. Figma 공부
3. 서비스 플로우 공유를 통해 프론트 엔드와 원활한 소통

**Comment by nailerHeum** [comment]
- DB schema 설계 문서 작업
    1. 대략적인 기능 관련 
    1. 진행 중인 기능들 중심으로 conceptual schema 작성
    2. physical schema 작성 중
    3. 권한 기능 관련 db 설계 진행 중

**Comment by pec9399** [comment]
- React, Redux, Redux-saga 공부 및 연동
- (공부를 위한) SignIn, SignUp Page 템플릿 적용
- DM page 작성 시작, websocket 연동
- 배포 서버 세팅, domain 및 SSL 적용, DB Server 적용

**Comment by hig4342** [comment]
* Redux, Redux-saga 공부
* [풀 캘린더](https://fullcalendar.io/) 오픈소스 공부
  * 프로젝트에서 만족하는 기능을 사용하도록 개발
  * 캘린더를 어느 페이지든 사용할수 있도록 캘린더 wrapper 제작
  * 서버와 원할한 데이터 교환을 위한 데이터 타입 정리
