### ISSUE TITLE
[API] GET Boards API 

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#54]
## GET Boards API 
- 커뮤니티의 id를 넘겨주었을 때, 해당 커뮤니티의 모든 게시판들의 JSON List를 보내주는 API
- Header 또는 Main 페이지, 게시글 생성페이지의 게시판 선택 시 필요

### `req`
1. req body로 `community_id` 보내기
2. req header의 token 정보로 user를 확인하고, user의 연결된 community_id를 통해 boardList 응답하기

2번의 방법이 더 안전할 듯 싶습니다.

### `res`
  - boardList: Board[] / 모든 게시판의 데이터 리스트
  - counts: Int / 게시판 개수

**Comment by pec9399** [comment]
GET Boards API 2번 방법으로 구현했습니다. 아직 유저 부대 선택기능이 만들어지지 않아서 저같은 경우 1번 부대로 넣어두고 테스트 했습니다 (테스트 하시려면 공용 db 서버에 데이터 있습니다)

**Comment by nailerHeum** [comment]
구현 내용 확인했습니다. 추가적인 요청 사항 발생하면 열어주시면 됩니다.
