### ISSUE TITLE
게시판 타입 (Grid / List) 논의

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#57]
게시판 View (게시글 목록 페이지)의 형태에 대해 논의를 하고 싶습니다.

제가 생각하는 게시판 타입은 Grid와 List 2가지 이며, 각각 mobile과 PC 버전의 View를 고려할 수 있습니다.

Grid형, List형 중 하나의 형태만을 선택해서 개발하는 방법과 두가지 타입 모두 개발 후 게시판 생성 시 관리자가 선택하는 방법 중 어떤 방법이 좋을 지 논의하면 좋겠습니다.

아래는 예시입니다.

### Grid (Timeline형) 예시
- Instagram
<img src="https://user-images.githubusercontent.com/39655003/134765314-62c45fe3-5cce-4977-89b0-788a890835d0.png" alt="drawing" width="150"/>

- Youtube
<img src="https://user-images.githubusercontent.com/39655003/134765403-7526409d-0289-4129-9da7-8e6c5778d23a.png" alt="drawing" width="150"/>

### List형 예시
- 에브리타임
<img src="https://user-images.githubusercontent.com/39655003/134765426-7b35d8e3-2ecf-4964-849a-cccdbac3625a.png" alt="drawing" width="150"/>

### Grid형 예시
- Velog
<img src="https://user-images.githubusercontent.com/39655003/134765473-03f4a69b-629d-44b3-9626-c3b8f78521ac.png" alt="drawing" width="500"/>

- 학교가 불편한 순간
<img src="https://user-images.githubusercontent.com/39655003/134765489-aaaf43b6-9250-4f04-868b-8b01ea0741d5.png" alt="drawing" width="500"/>

### List형 예시
- 에브리타임
<img src="https://user-images.githubusercontent.com/39655003/134765500-d8b880c0-cb66-4931-b898-7001c724e3b8.png" alt="drawing" width="500"/>

**Comment by pec9399** [comment]
저는 시간만 된다면 후자가 좋을 것 같습니다. 혹은 뷰 형식을 관리자가 아닌 사용자가 선택할 수 있게 해도 좋을 것 같습니다.

**Comment by bwmelon97** [comment]
- Toggle로 사용자가 UI 선택
- List형 먼저 개발
