### ISSUE TITLE
사용자 회원가입 기능

### ISSUE THREAD

**Issue by pec9399** [osamhack2021/WEB_Millage_ICM#63]
부대코드 등을 활용한 인증 후 개인정보로 회원가입

**Comment by thn02046** [comment]
부대코드이외에 인증시 어떤 요소들을 더 입력받을 예정인가요?

**Comment by pec9399** [comment]
일단 ID, Password, Email (혹은 전화번호), 이름, 닉네임 정도입니다. 추후에 추가가 될 가능성은 있습니다.
