### ISSUE TITLE
Open Source 활동 커뮤니티

### ISSUE THREAD

**Issue by pec9399** [osamhack2021/WEB_Millage_ICM#66]
본인이 가입되어 있으신 Open Source 커뮤니티를 댓글로 남겨주세요!

**Comment by pec9399** [comment]
Korea Docker User Group - https://www.facebook.com/groups/korea.docker.user.group
Node.js Korea - https://www.facebook.com/groups/nodejskr
Kubernetes Korea Group - https://www.facebook.com/groups/k8skr
생활코딩 - https://www.facebook.com/groups/codingeverybody

**Comment by bwmelon97** [comment]
멘토님이 공유해주셨던 Scouter OSS ARM 페이스북 그룹입니다.
Scouter OSS ARM - https://www.facebook.com/groups/scouterapm

**Comment by thn02046** [comment]
구글 Flutter 한국 사용자 모임 - https://www.facebook.com/groups/283396125525261/?action_source=group_mall_recommendation_affordance
생활코딩 - https://www.facebook.com/groups/codingeverybody
Scouter OSS ARM - https://www.facebook.com/groups/scouterapm

SNS 계정 생성 후 위 커뮤니티들에 가입 요청하였습니다.

**Comment by hig4342** [comment]
생활코딩 - https://www.facebook.com/groups/codingeverybody
코딩이랑 무관합니다만, - https://www.facebook.com/groups/System.out.Coding
Vue.js Korea - https://www.facebook.com/groups/vuejs.korea
AWSKRUG- AWS한국사용자모임 - https://www.facebook.com/groups/awskrug

**Comment by nailerHeum** [comment]
AWSKRUG- AWS한국사용자모임 - https://www.facebook.com/groups/awskrug
한국 러스트 사용자 그룹 - https://www.facebook.com/groups/rustlang
자바스크립트 개발자 포럼 - https://www.facebook.com/groups/jsdev.kr
