### ISSUE TITLE
사용자 부대선택 페이지

### ISSUE THREAD

**Issue by pec9399** [osamhack2021/WEB_Millage_ICM#71]
사용자가 회원가입 시 부대선택을 하는 페이지입니다.

부대목록 / 검색 기능이 포함됩니다

https://everytime.kr/register

**Comment by thn02046** [comment]
국군 대대목록을 검색해 보았는데 https://namu.wiki/w/%EB%8C%80%EB%8C%80 해당 페이지가 가장 많은 대대 목록을 포함하고 있는것 같습니다. 하지만 포함되어있지 않은 대대도 있는것 같은데 혹시 대대 목록을 어디에서 구할 수 있는지 아시는분 있을까요?

**Comment by bwmelon97** [comment]
국방망 인트라넷에서 국방부 홈페이지에 찾아보면 있지 않을까 예측해봅니다..!

내일 업무시간에 가능하다면 찾아보겠습니다 !

**Comment by thn02046** [comment]
저도 찾아보겠습니다!

**Comment by bwmelon97** [comment]
해당 기능이 유저 가입 시에 사용되는 것이라면, 생성된 커뮤니티에 한해서 검색을 제공하는 것은 어떨까요?
커뮤니티가 만들어지지 않은 부대의 병사들은 어차피 사용할 수가 없기 때문에, 검색결과에 나오지 않아도 괜찮지 않을까 싶습니다.

(예전에 저희 학교에서 에타 커뮤니티를 생성하기 전에 제가 에타에 가입하려 했을 때, 학교가 검색창에 나오지 않았던 것이 기억납니다.)

**Comment by pec9399** [comment]
저도 수근님 말씀대로 등록된 부대만 추가하려 했습니다! 예시로 많이 넣어두긴 할테지만요.

**Comment by pec9399** [comment]
1차적으로 완성하고 추후 디자인이 완성되면 다시 디자인 예정입니다
